### ISSUE TITLE
Failed to fetch version info for user/repo

### ISSUE THREAD

**Issue by akhilarjun** [jsdelivr/jsdelivr#18243]
I see this issue is a repetition of old one in May #18216 

I am facing the same issue for my repo: https://cdn.jsdelivr.net/gh/akhilarjun/tinylibs@latest/themejs/theme.js

I tried pushing a new release, but no help

**Comment by Alvin9999** [comment]
me too

**Comment by akhilarjun** [comment]
It got auto-resolved for me. So I think it might be an intermittent issue.

**Comment by Alvin9999** [comment]
me too. haha~

**Comment by jimaek** [comment]
The issue comes from our service hitting GitHub's rate limits. But it should only happen on new files that have not yet been cached.
Soon we are going to deploy some updates to lower the amount of requests we send to GitHub's API.

**Comment by ekinops-india** [comment]
Hi , i have created private repo in github , and trying to access files through js delivr 
https://cdn.jsdelivr.net/gh/ekinops-india/minifyjscss/main/jquery.js , 
getting below error
Failed to fetch version info for ekinops-india/minifyjscss.
also tried by changing the repo visibility to public but no help

**Comment by jimaek** [comment]
We don't support private repos, sorry

**Comment by sadmiral98** [comment]
2020's problem still happening at the end of 2024. how can it be?

my repo is public and its fine 1 day after i try using jsdelivr
and then the next day its already error, 
i didnt have any branch so its on main.
using /repo@main/ didnt solve the issue

**Comment by HackyRoot** [comment]
I'm facing the same issue. Yesterday it was working just fine. But today it showing me error. I didn't change the code or didn't make any changes in the repo as well.
```
Failed to fetch version info for user/repo.
```

**Comment by rafaellkm** [comment]
me too

**Comment by MartinKolarik** [comment]
Sorry, there was a temporary configuration issue that we've just fixed, it should work now.

**Comment by cro74** [comment]
The error still exists by me :-(
https://cdn.jsdelivr.net/gh/tsq456/picBed@latest/master/bg.png
https://cdn.jsdelivr.net/gh/cro74/repo_test/test.html

**Comment by domdfcoding** [comment]
I have started seeing this since yesterday on several repos. Currently affecting https://cdn.jsdelivr.net/gh/domdfcoding/folium-about-button/ since this morning. Yesterday's problem ones fixed themselves after a few hours (presumably once the GitHub rate limit expired)

Edit: by the time I'd written this the landing page now loads but the newly released version (from about 3 hours ago) still doesn't show in the dropdown, and refreshing the page goes back to the error message.
