### ISSUE TITLE
404 bug?

### ISSUE THREAD

**Issue by angoras** [jsdelivr/jsdelivr#3814]
When trying to get:
http://cdn.jsdelivr.net/g/angularjs(angular.min.js+angular-route.min.js),foundation(js/foundation.min.js+js/foundation/foundation.reveal.js)
directly I get the correct reply just fine.

But when including it in a page like:
`<script src="//cdn.jsdelivr.net/g/angularjs(angular.min.js+angular-route.min.js),foundation(js/foundation.min.js+js/foundation/foundation.reveal.js)"></script>`
I get 404 Not Found http://cdn.jsdelivr.net/g/angularjs(angular.min.js+angular-route.min.js),foundation(js/foundation.min.js+js/foundation/angular-route.min.js.map
instead.

Tried in latest Chrome. Note that the end is wrong, foundation-reveal has been replaced by angular-route. Is my syntax wrong, or is this a bug?

**Comment by jimaek** [comment]
Its not a bug. angular-route.min.js.map doesnt exist here https://github.com/jsdelivr/jsdelivr/tree/master/files/foundation/5.5.1/js/foundation

Can you give me more details about what you are trying to do? Because I am confused.

**Comment by angoras** [comment]
Well, the thing is I never try to get angular-route.min.js.map, it's just inserted somehow instead of foundation.reveal.js.

**Comment by jimaek** [comment]
What do you mean inserted? jsDelivr cant change the URLs. Its completely up to the user to configure the correct URL and files

**Comment by angoras** [comment]
I'm not sure what's happening, but this is my code:
`<script src="//cdn.jsdelivr.net/g/angularjs(angular.min.js+angular-route.min.js),foundation(js/foundation.min.js+js/foundation/foundation.reveal.js)"></script>`

And I get this back:
404 Not Found http://cdn.jsdelivr.net/g/angularjs(angular.min.js+angular-route.min.js),foundation(js/foundation.min.js+js/foundation/angular-route.min.js.map

Where does angular-route.min.js.map come from? :-)

**Comment by jimaek** [comment]
Can you send me a link to your website where I can see this error for myself?

**Comment by angoras** [comment]
Sure, here is a stripped down version of the problem:
http://dev.ipatch.se/jsdelivr/

Thanks for looking into this!

**Comment by jimaek** [comment]
I know what is happening. Angularjs has the following code inside:
`//# sourceMappingURL=angular-route.min.js.map`

It tries to load the map file and breaks the url while doing so. You can ignore for it now. The original URL loads just fine, this is an additional GET that the browser tries to do and fails. It doesnt impact your website in any way.

I will try to make sure that it doesn't return a 404 in these cases and the error will disappear. 

P.S. I can only see the error in Chrome. Firefox doesnt show any errors.

Thanks for reporting

**Comment by angoras** [comment]
Ah, of course! Thanks.

**Comment by angoras** [comment]
Is this supposed to be fixed now? I'm still getting the same error...

**Comment by jimaek** [comment]
Hey sorry it took so long. It should be fixed now, please check. You should not be seeing 404 errors any more

**Comment by angoras** [comment]
Checked, and I can confirm it's working. It is indeed in another castle! ;-)

Thanks!

**Comment by brgrz** [comment]
I'm still having issues with this. It does not produce a network error (404 or anything) but it does produce a console error saying "Failed to parse SourceMaps", which is annoying because it always opens the console when having the Developer tools open.

**Comment by jimaek** [comment]
There is no way around that. When you combine files you break the relative paths. There is no fix to that

**Comment by brgrz** [comment]
But how can we prevent Chrome from requesting the map files for grouped references? Network error would actually be better than returning a string that's not a source map at all.

**Comment by jimaek** [comment]
The browser requests those files only after you open the developer tools. They dont get downloaded otherwise. So there is no impact.
A 404 would indicate that there was an error while there wasnt.

**Comment by brgrz** [comment]
If the map doesn't exist the logical and semantical correct thing to do is to return a 404. Not "The map is in an other castle". No matter how cool that might sound.

If it is as you say that the request for the .map file only happens when opening Developer tools than I don't see how the 404 could present problems.

On the contrary, as it is now, my developer tools now open the console each and every time with a JS error which "Failed to parse SourceMap" clearly is. When I have my code error free I find it troublesome that the console keeps popping up because someone wrongfully decided to return some cool sentence which doesn't parse.

Maybe you could put that sentence in a JS function so the response could get parsed by the browser?

**Comment by jimaek** [comment]
A 404 jumps into eyes too much making people think something is VERY wrong. Especially since not everyone knows that that error appears only when the dev tools are open and not every single time. 
A simple console error does not create that fear. 
Right now I believe the current way is the best for the majority of users. 
If you find more people that believe your way is better then I am willing to rethink this.

The alternative is to simply use all files directly without /g/. Then the maps will be loaded correctly.
